manifest:
  remotes:
    - name: Nick-Munnich
      url-base: https://github.com/Nick-Munnich
    - name: sadekbaroudi
      url-base: https://github.com/sadekbaroudi
    # Add this:
    - name: halfdane
      url-base: https://github.com/halfdane/
  projects:
    - name: zmk
      remote: Nick-Munnich
      revision: layer-locking
      import: app/west.yml
    - name: zmk-fingerpunch-keyboards
      remote: sadekbaroudi
      revision: main
      import: config/deps.yml
    - name: zmk-fingerpunch-vik
      remote: sadekbaroudi
      revision: main
      import: config/deps.yml
    - name: zmk-fingerpunch-controllers
      remote: sadekbaroudi
      revision: main
      import: config/deps.yml
      # Halfdane
    - name: zmk-input-gestures
      remote: halfdane
      revision: main
    # Halfdane
    - name: zmk-input-processors
      remote: halfdane
      revision: main
    - name: cirque-input-module
      remote: halfdane
      revision: absolute_mode
  self:
    path: config